//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SSMIEntities : DbContext
    {
        public SSMIEntities()
            : base("name=SSMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<VW_USER_DETAILS> VW_USER_DETAILS { get; set; }
    
        public virtual ObjectResult<PR_ACCOUNTINGYEAR_ID_CHK_Result> PR_ACCOUNTINGYEAR_ID_CHK(Nullable<int> pFYear, Nullable<int> pTYear)
        {
            var pFYearParameter = pFYear.HasValue ?
                new ObjectParameter("PFYear", pFYear) :
                new ObjectParameter("PFYear", typeof(int));
    
            var pTYearParameter = pTYear.HasValue ?
                new ObjectParameter("PTYear", pTYear) :
                new ObjectParameter("PTYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ACCOUNTINGYEAR_ID_CHK_Result>("PR_ACCOUNTINGYEAR_ID_CHK", pFYearParameter, pTYearParameter);
        }
    
        public virtual ObjectResult<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result> PR_COMPANYACCOUNTINGDETAIL_ID_CHK(Nullable<int> pCompId, Nullable<int> pYrId)
        {
            var pCompIdParameter = pCompId.HasValue ?
                new ObjectParameter("PCompId", pCompId) :
                new ObjectParameter("PCompId", typeof(int));
    
            var pYrIdParameter = pYrId.HasValue ?
                new ObjectParameter("PYrId", pYrId) :
                new ObjectParameter("PYrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result>("PR_COMPANYACCOUNTINGDETAIL_ID_CHK", pCompIdParameter, pYrIdParameter);
        }
    
        public virtual ObjectResult<pr_CompanyDetail_Flx_Assgn_Result> pr_CompanyDetail_Flx_Assgn(Nullable<int> pCOMPID)
        {
            var pCOMPIDParameter = pCOMPID.HasValue ?
                new ObjectParameter("PCOMPID", pCOMPID) :
                new ObjectParameter("PCOMPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_CompanyDetail_Flx_Assgn_Result>("pr_CompanyDetail_Flx_Assgn", pCOMPIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchCompanyMaster_Result> pr_SearchCompanyMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCompanyMaster_Result>("pr_SearchCompanyMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchEmployeeMaster_Result> pr_SearchEmployeeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchEmployeeMaster_Result>("pr_SearchEmployeeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Roles_Result> pr_Search_Roles(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Roles_Result>("pr_Search_Roles", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchSalesOrder_Result> pr_SearchSalesOrder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid, Nullable<int> pEmplid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            var pEmplidParameter = pEmplid.HasValue ?
                new ObjectParameter("PEmplid", pEmplid) :
                new ObjectParameter("PEmplid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSalesOrder_Result>("pr_SearchSalesOrder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter, pEmplidParameter);
        }
    }
}
